# Generated by Django 2.2.3 on 2019-07-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
