# Generated by Django 2.2.3 on 2019-08-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_auto_20190807_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_date', '-updated', 'time_stamp'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
