# Generated by Django 2.2.3 on 2019-08-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0007_auto_20190807_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
